[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "perseus"
version = "0.1.0"
description = "Perseus - docs-as-code extractor (demo)"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "click>=8.0",
  "pydantic>=2.0",
  "jinja2>=3.0",
  "pyyaml>=6.0",
  "dependency-injector>=4.0",
  "python-dotenv>=1.0.1",
]

# Create a console script 'pers' that points to the CLI group in main.py
[project.scripts]
pers = "main:cli"

[tool.setuptools.packages.find]
where = ["."]
include = ["perseus"]
